server:
  port: 8763
#为服务命名
spring:
  application:
    name: eureka-client1
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
#  instance:
#    instance-id: 测试服务-8763  # 人性化显示出服务的信息
#    prefer-ip-address: true    # 访问路径可显示ip地址

logging:
  level:
    com:
      netflix.*: debug