---
spring:
  profiles: peer1
server:
  port: 8761

# 剔除自我保护机制
#Eviction-服务剔除
#默认情况下，当Eureka Client连续90秒没有向Eureka Server发送服务续约（即心跳）时，Eureka Server会将该服务实例从服务注册列表删除。
#Eureka的自我保护模式
#当一个新的Eureka Server出现时，会尝试从相邻的Peer节点获取所有服务实例的注册信息。如果从相邻的Peer节点获取信息时出现了故障，
#Eureka Server会尝试其它的Peer节点。如果Eureka Server能够成功获取所有的服务实例信息，则根据配置信息设置服务续约的阈值。
#在任何时间，如果Eureka Server接收到的服务续约低于该配置的百分比（默认为15分钟内低于85%），则服务器开启自我保护模式，
#即不在剔除注册列表的信息。这样做的好处是如果是Eureka Server自身的网络问题而导致Eureka Client无法续约，这样在注册列表中不会剔除注册信息，
#这样Eureka Client还可以被其他服务消费。同时这个功能也是有坑的postForLocation，如果在服务较少时，服务由于意外情况挂掉后很容易阈值就低于85%，
#由于自我保护导致挂掉的服务在注册列表中还是存在，但其它服务无法消费，这会迷惑开发人员排错的方向。如果需要关闭该功能，在配置文件中添加如下代码：
eureka:
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
# 开启所有断点
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: peer2
server:
  port: 8762

eureka:
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      netflix:
        discovery: debug